### PR TITLE
Add Composer support

### PR DESCRIPTION
**Pull request by pcalves**
Hey Craig!

I decided to take up on [your offer](https://github.com/ccampbell/chromephp/issues/22#issuecomment-12505229) and write a composer.json file for your class! Please check the data and see if everything is OK (especially in the description and authors and such).

Once you merged my changes, I'll submit the package [here](https://packagist.org/packages/submit). Composer is a dependency manager for PHP, it allows you to manage libraries and packages on a per-project basis. If you still do work with PHP you should check it out. :)

### CODE REVIEW

**Comment by ccampbell** [comment]
Cool! Only thing that looks off is that it should be Apache 2.0 license instead of MIT.

Is there any sort of field where there could be a link to the actual browser extension or website?  

http://chromephp.com/
https://chrome.google.com/webstore/detail/chromephp/noaneddfkdjfnfdakjjmocngnfkfehhd

**Comment by pcalves** [comment]
Done and done! If we're linking to http://chromephp.com, it'd be cool to include something there to let people know the package can be installed through Composer, but I understand if that's too much work. It's great just to be able to use this with Composer myself.

**Comment by ccampbell** [comment]
Merged! Is there a link or special instructions on how to install using composer? I guess let me know once you have submitted it, and I can add a link or something on the site.

**Comment by pcalves** [comment]
Awesome, thanks! I've submitted the package, it's already up on Packagist: https://packagist.org/packages/ccampbell/chromephp

As for the installation, the usual instructions are:

Install [Composer](http://getcomposer.org/doc/01-basic-usage.md#installation):

``` bash
curl -s https://getcomposer.org/installer | php
```

Create a **composer.json** file in your project **root**:

``` json
{
    "require": {
        "ccampbell/chromephp": "dev-master"
    }
}
```

Install package via Composer:

``` bash
php composer.phar install
```

The main step though, and really the only thing someone who uses Composer needs, is the JSON code — to know how to include the package.

**Pull request merged**
